name: stylegan2-k
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pip
  - numpy=1.19.2
  - click=7.1.2
  - pillow=7.0.0
  - scipy=1.5.2
  - pytorch=1.8.0
  - torchvision=0.9.0
  - cudatoolkit=11.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - imageio=2.9.0
  - tensorboard=1.15.0
  - psutil=5.7.2
  - ipython=7.19.0
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng==0.1.0
    - pyyaml==6.0
    - scikit-image==0.15.0
    - scikit-learn==0.23.2
    - numba==0.51.2
    - matplotlib==3.3.3
    - opencv-python==4.4.0.46