load_ckpt:  # weight path to be pruned
outdir: # save path for the pruned weights
num_gpus: 1 # number of GPUs
random_seed: 0

data: # dataset path
cond: # Train conditional model based on dataset labels [default: false] <bool>
subset: # None: all
mirror: True # apply x-flip: <bool>

cfg: paper256 # auto, stylegan2, paper256, paper512, paper1024, cifar

aug: noaug # None (ada), noaug, fixed
p:  # Specify p for "fixed" (required): <float>
target: # 
augpipe: #

resume: # weight path for resuming
freezed: #

fp32: #
nhwc: #
allow_tf32: #
nobench: #
workers: #

### GAN Slimming pruning
pruning_criterion: CAGC # [GS | CAGC]
pruning_ratio: 0.9 # default = 0.7
n_sample: 400 # number of samples for estimation, default = 400
batch: 8 # size of the batch for estimation, default = 10
noise_prob: 0.05 # default = 0.05